---
index: index.md
categories:
  - aws:
    - doingthingsinaws.md
    - someOtherStuff.md
  - haskell:
    - learningHaskell.md
  - python:
    - making_a_static_site.md
    - dataclasses.md
    - someOtherThing.md
style: dark