---
index: test.md
categories:
  - aws:
    - doingthingsinaws.md
    - someOtherStuff.md
  - haskell:
    - learningHaskell.md
  - python:
    - examples/making_a_static_site.md
    - examples/dataclasses.md
    - examples/someOtherThing.md
style: dark